---
version: 2.1

orbs:
  terraform: twdps/terraform@0.6.0
  do: twdps/pipeline-events@0.2.0

# ==== global pipeline parameters

parameters:
  # since v2.0.0 of the circleci-infra-aws executor is currently on tf 1.3.3, skip install
  # terraform-version:
  #   description: terraform version for all jobs
  #   type: string
  #   default: "1.3.3"
  executor-image:
    description: image to use for terraform runs
    type: string
    default: twdps/circleci-infra-aws:alpine-2.0.0

# ==== triggers

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: set terraform backend
    steps:
      - run:
          name: set ~/.terraformrc
          command: bash scripts/tf_backend.sh

jobs:

  update-dashboard:
    docker:
      - image: << pipeline.parameters.executor-image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update datadog cluster monitors
          command: python scripts/deploy_dashboard.py

  update-monitors:
    parameters:
      env:
        description: which op-connect instance
        type: string
      instance:
        description: tag\alb filters
        type: string
      cluster:
        description: ecs-cluster where service runs
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update datadog dashboard
          command: python scripts/deploy_monitors.py << parameters.env >> << parameters.cluster >> << parameters.instance >>

  account-level-credentials:
    parameters:
      instance:
        description: name of environments file
        type: string
      key:
        description: name of credential to create
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: create secretes manager key entry if not already present
          command: |
            bash scripts/create_secrets_manager_entry.sh << parameters.instance>> << parameters.key >>

  integration-test:
    docker:
      - image: << pipeline.parameters.executor-image >>
    parameters:
      instance:
        description: instance identifier
        type: string
      vault:
        description: vault from which to fetch test key/value
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: smoke test op-connect server
          command: bash scripts/test_server.sh << parameters.instance >> << parameters.vault >>

workflows:
  version: 2

  deploy test instance:
    jobs:
      - account-level-credentials:
          name: account credentials for test instance
          instance: test
          key: "test-op-connect-credential-file"
          filters: *on-push-main

      - terraform/plan:
          name: change plan for test instance
          workspace: test
          var-file: environments/test.json
          extra-terraform-args: -var="op_credentials_file_base64=${TEST_OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - account credentials for test instance
          filters: *on-push-main

      - approve changes to test instance:
          type: approval
          requires:
            - change plan for test instance
          filters: *on-push-main

      - terraform/apply:
          name: apply changes to test instance
          workspace: test
          var-file: environments/test.json
          extra-terraform-args: -var="op_credentials_file_base64=${TEST_OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          after-terraform:
            - do/circle-deploy
            - do/slack-webhook:
                message: lab-service-op-connect-server test instance deployment
                webhook-url: $LAB_EVENTS_CHANNEL_WEBHOOK
          requires:
            - approve changes to test instance
          filters: *on-push-main

      - integration-test:
          name: test instance integration tests
          instance: test
          vault: empc-lab-test
          requires:
            - apply changes to test instance
          filters: *on-push-main

      - update-dashboard:
          context: twdps-core-labs-team
          filters: *on-push-main

      - update-monitors:
          name: update test instance monitors
          env: test
          cluster: test-op-connect
          instance: test-op-connect-api-alb
          context: twdps-core-labs-team
          filters: *on-push-main

  release prod instance:
    jobs:
      - account-level-credentials:
          name: account credentials for prod instance
          instance: prod
          key: "op-connect-credential-file"
          filters: *on-tag-main

      - terraform/plan:
          name: change plan for prod instance
          workspace: prod
          var-file: environments/prod.json
          extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - account credentials for prod instance
          filters: *on-tag-main

      - approve changes to prod instance:
          type: approval
          requires:
            - change plan for prod instance
          filters: *on-tag-main

      - terraform/apply:
          name: apply changes to prod instance
          workspace: prod
          var-file: environments/prod.json
          extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          after-terraform:
            - do/circle-deploy
            - do/slack-webhook:
                message: lab-service-op-connect-server production release
                webhook-url: $LAB_EVENTS_CHANNEL_WEBHOOK
          requires:
            - approve changes to prod instance
          filters: *on-tag-main

      - integration-test:
          name: prod instance integration tests
          instance: prod
          vault: empc-lab
          requires:
            - apply changes to prod instance
          filters: *on-tag-main

      - update-monitors:
          name: update prod instance monitors
          env: prod
          cluster: op-connect
          instance: op-connect-api-alb
          context: twdps-core-labs-team
          filters: *on-tag-main

  release cohort instance:
    jobs:
      - account-level-credentials:
          name: account credentials for cohorts instance
          instance: cohorts
          key: "cohorts-op-connect-credential-file"
          filters: *on-tag-main

      - terraform/plan:
          name: change plan for cohorts instance
          workspace: cohorts
          var-file: environments/cohorts.json
          extra-terraform-args: -var="op_credentials_file_base64=${COHORTS_OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - account credentials for cohorts instance
          filters: *on-tag-main

      - approve changes to cohorts instance:
          type: approval
          requires:
            - change plan for cohorts instance
          filters: *on-tag-main

      - terraform/apply:
          name: apply changes to cohorts instance
          workspace: cohorts
          var-file: environments/cohorts.json
          extra-terraform-args: -var="op_credentials_file_base64=${COHORTS_OP_CREDENTIAL_FILE_BASE64}"
          # terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          after-terraform:
            - do/circle-deploy
            - do/slack-webhook:
                message: lab-service-op-connect-server cohorts release
                webhook-url: $LAB_EVENTS_CHANNEL_WEBHOOK
          requires:
            - approve changes to cohorts instance
          filters: *on-tag-main

      - integration-test:
          name: cohorts instance integration tests
          instance: cohorts
          vault: cohorts
          requires:
            - apply changes to cohorts instance
          filters: *on-tag-main

      - update-monitors:
          name: update cohorts instance monitors
          env: cohorts
          cluster: cohorts-op-connect
          instance: cohorts-op-connect-api-alb
          context: twdps-core-labs-team
          filters: *on-tag-main

  # generate-release-notes:
  #   jobs:
  #     - do/release-notes:
  #         name: generate release notes
  #         context: twdps-core-labs-team
  #         shell: op run --env-file op.env -- /bin/bash
  #         on-tag: true
  #         filters: *on-tag-main


  # uncomment this workflow to do a full teardown of either instance
  #
  # lab-service-op-connect-server-teardown:
  #   jobs:
  #     - approve-test-teardown:
  #         type: approval
  #         filters: *on-push-main

  #     - terraform/destroy:
  #         name: delete-test-op-connect-server-resources
  #         workspace: test
  #         var-file: environments/test.json
  #         extra-terraform-args: -var="op_credentials_file_base64=${TEST_OP_CREDENTIAL_FILE_BASE64}"
  #         terraform-version: << pipeline.parameters.terraform-version >>
  #         before-terraform:
  #           - set-environment
  #         requires:
  #           - approve-test-teardown
  #         filters: *on-push-main

  #     - approve-prod-teardown:
  #         type: approval
  #         filters: *on-push-main

  #     - terraform/destroy:
  #         name: delete-prod-op-connect-server-resources
  #         workspace: prod
  #         var-file: environments/prod.json
  #         extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
  #         terraform-version: << pipeline.parameters.terraform-version >>
  #         before-terraform:
  #           - set-environment
  #         requires:
  #           - approve-prod-teardown
  #         filters: *on-push-main

  #     - terraform/destroy:
  #         name: delete-cohort-op-connect-server-resources
  #         workspace: cohort
  #         var-file: environments/cohort.json
  #         extra-terraform-args: -var="op_credentials_file_base64=${COHORT_OP_CREDENTIAL_FILE_BASE64}"
  #         terraform-version: << pipeline.parameters.terraform-version >>
  #         before-terraform:
  #           - set-environment
  #         requires:
  #           - approve-cohort-teardown
  #         filters: *on-push-main
