---
version: 2.1

orbs:
  terraform: twdps/terraform@0.5.0
  # used for github-release-notes feature
  executor-tools: twdps/executor-tools@0.4.0

# ==== global pipeline parameters

parameters:
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.1.9"
  executor-image:
    description: image to use for terraform runs
    type: string
    default: twdps/circleci-infra-aws:alpine-1.6.0

# git push: deploy sandbox
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release to preview cluster
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: set terraform backend
    steps:
      - run:
          name: set ~/.terraformrc
          command: bash scripts/tf_backend.sh

jobs:

  update-dashboard:
    parameters:
      shell-options:
        description: shell configuration shell-options
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update datadog cluster monitors
          command: python scripts/deploy_dashboard.py

  update-monitors:
    parameters:
      env:
        description: which op-connect instance, sandbox or preview
        type: string
      instance:
        description: tag\alb filters
        type: string
      cluster:
        description: ecs-cluster where service runs
        type: string
      shell-options:
        description: shell configuration shell-options
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update datadog dashboard
          command: python scripts/deploy_monitors.py << parameters.env >> << parameters.cluster >> << parameters.instance >>

  account-level-credentials:
    parameters:
      instance:
        description: name of environments file
        type: string
      key:
        description: name of credential to create
        type: string
    docker:
      - image: << pipeline.parameters.executor-image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: create secretes manager key entry if not already present
          command: |
            bash scripts/create_secrets_manager_entry.sh << parameters.instance>> << parameters.key >>

workflows:
  version: 2

  lab-service-op-connect-server-sandbox:
    jobs:
      # sandbox deployment
      - account-level-credentials:
          name: nonprod-account-credentials
          instance: sandbox
          key: "sandbox-op-connect-credential-file"
          filters: *on-push-main

      - terraform/plan:
          name: sandbox-change-plan
          workspace: sandbox
          var-file: environments/sandbox.json
          extra-terraform-args: -var="op_credentials_file_base64=${SANDBOX_OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          filters: *on-push-main

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: apply-sandbox-changes
          workspace: sandbox
          var-file: environments/sandbox.json
          extra-terraform-args: -var="op_credentials_file_base64=${SANDBOX_OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - approve-sandbox-changes
          filters: *on-push-main
      
      - update-dashboard:
          context: twdps-core-labs-team
          shell-options: op run --env-file op.env -- /bin/bash
          filters: *on-push-main

      - update-monitors:
          name: update-sandbox-monitors
          env: sandbox
          cluster: sandbox-op-connect
          instance: sandbox-op-connect-api-alb
          context: twdps-core-labs-team
          shell-options: op run --env-file op.env -- /bin/bash
          filters: *on-push-main

  lab-service-op-connect-server-preview:
    jobs:
      # production deployment, uses preview cluster network space
      - account-level-credentials:
          name: preview-account-credentials
          instance: preview
          key: "op-connect-credential-file"
          filters: *on-tag-main

      - terraform/plan:
          name: preview-change-plan
          workspace: preview
          var-file: environments/preview.json
          extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          filters: *on-tag-main

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: apply-preview-changes
          workspace: preview
          var-file: environments/preview.json
          extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - approve-preview-changes
          filters: *on-tag-main

      - update-monitors:
          name: update-preview-monitors
          env: preview
          cluster: op-connect
          instance: op-connect-api-alb
          context: twdps-core-labs-team
          shell-options: op run --env-file op.env -- /bin/bash
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          name: release-lab-service-op-connect
          context: twdps-core-labs-team
          shell: op run --env-file op.env -- /bin/bash
          on-tag: true
          filters: *on-tag-main


  # uncomment this workflow to do a full teardown of either instance
  
  lab-service-op-connect-server-teardown:
    jobs:
      - approve-sandbox-teardown:
          type: approval
          filters: *on-push-main

      - terraform/destroy:
          name: delete-sandbox-op-connect-server-resources
          workspace: sandbox
          var-file: environments/sandbox.json
          extra-terraform-args: -var="op_credentials_file_base64=${SANDBOX_OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - approve-sandbox-teardown
          filters: *on-push-main

      - approve-preview-teardown:
          type: approval
          filters: *on-push-main

      - terraform/destroy:
          name: delete-preview-op-connect-server-resources
          workspace: preview
          var-file: environments/preview.json
          extra-terraform-args: -var="op_credentials_file_base64=${OP_CREDENTIAL_FILE_BASE64}"
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment
          requires:
            - approve-preview-teardown
          filters: *on-push-main
